/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Match {
  'id' : bigint,
  'status' : string,
  'teamAId' : bigint,
  'teamBId' : bigint,
  'innings' : Array<bigint>,
  'oversLimit' : bigint,
  'currentBowlerId' : [] | [bigint],
  'tournamentId' : bigint,
}
export interface Player {
  'id' : bigint,
  'name' : string,
  'teamId' : [] | [bigint],
}
export interface Team {
  'id' : bigint,
  'name' : string,
  'players' : Array<bigint>,
  'tournamentId' : bigint,
  'captainId' : [] | [bigint],
}
export type Time = bigint;
export interface Tournament {
  'id' : bigint,
  'teams' : Array<bigint>,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : string,
  'matches' : Array<bigint>,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBall' : ActorMethod<
    [bigint, bigint, bigint, bigint, boolean, boolean, boolean],
    undefined
  >,
  'addOverwiseScore' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[bigint, bigint, bigint, bigint], bigint>,
  'createPlayer' : ActorMethod<[string, [] | [bigint]], bigint>,
  'createTeam' : ActorMethod<[string, bigint], bigint>,
  'createTournament' : ActorMethod<[string, string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[bigint], [] | [Match]>,
  'getOverwiseScores' : ActorMethod<[bigint], Array<bigint>>,
  'getPlayer' : ActorMethod<[bigint], [] | [Player]>,
  'getTeam' : ActorMethod<[bigint], [] | [Team]>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getTournamentSnapshot' : ActorMethod<[bigint], [] | [Tournament]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMatches' : ActorMethod<[bigint], Array<Match>>,
  'listPlayers' : ActorMethod<[[] | [bigint]], Array<Player>>,
  'listTeams' : ActorMethod<[bigint], Array<Team>>,
  'listTournaments' : ActorMethod<[], Array<Tournament>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];