/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'teamAId' : IDL.Nat,
  'teamBId' : IDL.Nat,
  'innings' : IDL.Vec(IDL.Nat),
  'oversLimit' : IDL.Nat,
  'currentBowlerId' : IDL.Opt(IDL.Nat),
  'tournamentId' : IDL.Nat,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'teamId' : IDL.Opt(IDL.Nat),
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'players' : IDL.Vec(IDL.Nat),
  'tournamentId' : IDL.Nat,
  'captainId' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'teams' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'matches' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBall' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'addOverwiseScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createPlayer' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'createTeam' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'createTournament' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getOverwiseScores' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
  'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournamentSnapshot' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Tournament)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMatches' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
  'listPlayers' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Player)], ['query']),
  'listTeams' : IDL.Func([IDL.Nat], [IDL.Vec(Team)], ['query']),
  'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'teamAId' : IDL.Nat,
    'teamBId' : IDL.Nat,
    'innings' : IDL.Vec(IDL.Nat),
    'oversLimit' : IDL.Nat,
    'currentBowlerId' : IDL.Opt(IDL.Nat),
    'tournamentId' : IDL.Nat,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'teamId' : IDL.Opt(IDL.Nat),
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'players' : IDL.Vec(IDL.Nat),
    'tournamentId' : IDL.Nat,
    'captainId' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'teams' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'matches' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBall' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'addOverwiseScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createPlayer' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
    'createTeam' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'createTournament' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getOverwiseScores' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournamentSnapshot' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Tournament)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMatches' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
    'listPlayers' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Player)], ['query']),
    'listTeams' : IDL.Func([IDL.Nat], [IDL.Vec(Team)], ['query']),
    'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };